---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prop-devel
  name: reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims", "deployments", "statefulsets", "ingresses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prop-devel
  name: editor
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims", "deployments", "statefulsets", "ingresses"]
  verbs: ["get", "watch", "list", "update", "patch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prop-devel
  name: admin
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims", "deployments", "statefulsets", "ingresses"]
  verbs: ["get", "watch", "list", "update", "patch", "create", "delete"]
